version: '3'

services:
  websocket-chat-example:
    build: .
    container_name: websocket-chat-example
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080

volumes:
  node_modules:
